gbm with cross-validation
=======================

Setup
```{r setup}
## Libs
library(gbm)
library(cvTools)

## Data
load("../lm/trainC.Rdata")

test <- TRUE
if(test) {
	trainC <- trainC[1:1000, ]
}

rmlspe <- function(y, yHat, includeSE = FALSE) {
	rmspe(log(y + 1), log(yHat + 1), includeSE = includeSE)
}

# Remove date and transform the logical vectors into factors
fixStuff <- function(input) {
	res <- input[, !colnames(input) %in% "date"]
	res$business.categories.BeautySpas <- factor(res$business.categories.BeautySpas)
	res$business.categories.Food <- factor(res$business.categories.Food)
	res$business.categories.Restaurants <- factor(res$business.categories.Restaurants)
	res$business.categories.Shopping <- factor(res$business.categories.Shopping)
	res$business.open <- factor(res$business.open)
	return(res)
}
trainC <- fixStuff(trainC)
validateC <- fixStuff(validateC)
```


Just fit one gbm with 10-fold CV
```{r models}

## Fit gbm
fit.gbm.pois <- gbm(votes.useful ~ ., data=trainC, distribution="poisson", cv.folds=10)
#summary(fit.gbm.pois)
pretty.gbm.tree(fit.gbm.pois)
show(fit.gbm.pois)

## Evaluate with validation data set
pred.pois <- predict(fit.gbm.pois, validateC, type="response")
e.gbm.pois <- rmlspe(validateC$votes.useful, pred.pois, includeSE=TRUE)
e.gbm.pois
summary(pred.pois)

save(fit.gbm.pois, e.gbm.pois, file="gbm.Rdata")
```

Reproducibility
```{r reproduc}
print(proc.time())
sessionInfo()
```
