glm with cross-validation
=======================

Setup
```{r setup}
## Libs
library(cvTools)

## Data
load("../lm/trainC.Rdata")

test <- TRUE
if(test) {
	trainC <- trainC[1:100, ]
}
rmlspe <- function(y, yHat, includeSE = FALSE) {
	rmspe(log(y + 1), log(yHat + 1), includeSE = includeSE)
}
```


Fit 10-fold cross validation with 5 repetitions
```{r models}
## Fit binomial the models
fit.bin <- glm(votes.useful ~., data=trainC)
fit.bin.aic <- step(fit.bin, trace=0)
fit.bin.bic <- step(fit.bin, trace=0, k=log(nrow(trainC)))
summary(fit.bin)
summary(fit.bin.aic)
summary(fit.bin.bic)

## Fit poisson the models
fit.pois <- glm(votes.useful ~., data=trainC, family=poisson)
fit.pois.aic <- step(fit.pois, trace=0)
fit.pois.bic <- step(fit.pois, trace=0, k=log(nrow(trainC)))
summary(fit.pois)
summary(fit.pois.aic)
summary(fit.pois.bic)

## Determine the folds
seed <- 20130501
K <- 10
R <- 5
set.seed(seed)
folds <- cvFolds(nrow(trainC), K=K, R=R)

## Run the cross-validation
cv.bin <- cvFit(fit.bin, y=trainC$votes.useful, data=trainC, cost=rmlspe, costArgs=list(includeSE=TRUE), folds=folds)
cv.bin.aic <- cvFit(fit.bin.aic, y=trainC$votes.useful, data=trainC, cost=rmlspe, costArgs=list(includeSE=TRUE), folds=folds)
cv.bin.bic <- cvFit(fit.bin.bic, y=trainC$votes.useful, data=trainC, cost=rmlspe, costArgs=list(includeSE=TRUE), folds=folds)
cv.pois <- cvFit(fit.pois, y=trainC$votes.useful, data=trainC, cost=rmlspe, costArgs=list(includeSE=TRUE), folds=folds)
cv.pois.aic <- cvFit(fit.pois.aic, y=trainC$votes.useful, data=trainC, cost=rmlspe, costArgs=list(includeSE=TRUE), folds=folds)
cv.pois.bic <- cvFit(fit.pois.bic, y=trainC$votes.useful, data=trainC, cost=rmlspe, costArgs=list(includeSE=TRUE), folds=folds)

cv.sel <- cvSelect("bin"=cv.bin, "bin.aic"=cv.bin.aic, "bin.bic"=cv.bin.bic, "pois"=cv.pois, "pois.aic"=cv.pois.aic, "pois.bic"=cv.pois.bic)
cv.sel
cv.sel$se
cv.sel$reps

## Evaluate with validation data set
e.bin <- rmlspe(validateC$votes.useful, predict(fit.bin, validateC), includeSE=TRUE)
e.bin.aic <- rmlspe(validateC$votes.useful, predict(fit.bin.aic, validateC), includeSE=TRUE)
e.bin.bic <- rmlspe(validateC$votes.useful, predict(fit.bin.bic, validateC), includeSE=TRUE)
e.pois <- rmlspe(validateC$votes.useful, predict(fit.pois, validateC), includeSE=TRUE)
e.pois.aic <- rmlspe(validateC$votes.useful, predict(fit.pois.aic, validateC), includeSE=TRUE)
e.pois.bic <- rmlspe(validateC$votes.useful, predict(fit.pois.bic, validateC), includeSE=TRUE)
e.glm <- list(e.bin, e.bin.aic, e.bin.bic, e.pois, e.pois.aic, e.pois.bic)
names(e.glm) <- as.character(cv.sel$cv$Fit)
unlist(lapply(e.glm, function(x) { x$rmspe}))

rm(validateC, trainC, test, seed, K, R)
save.image(file="glm.Rdata")
```

Reproducibility
```{r reproduc}
print(proc.time())
sessionInfo()
```
